version: "3.3"
services:
    db:
        image: mysql:5
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - backend-network
        environment:
            - MYSQL_DATABASE=binance_future_ratios
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - 3306:3306
    app:
        build: .
        restart: always
        networks:
            - backend-network
        ports:
            - 5000:5000

volumes:
    db-data:
networks:
    backend-network: